FundamentosPlay/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import apiREST
from .views import home, students, teachers ,assistant




urlpatterns = [

    path('', home.home, name='home'),
    path('profile/<str:username>/', home.view_profile, name='profile'),
    path('noticias', home.noticias, name='noticias'),
    path('informacion', home.informacion, name='informacion'),
    path('descarga', home.descarga, name='descarga'),
    path('faq', home.faq, name='faq'),
    path('leaderboard', home.leaderboard, name='leaderboard'),



   #______________________________  URLS PARA  ADMINISTRACIÓN ________________________ no tocar :v
    path('students/', include(([
        path('', students.StadisticsView, name='quiz_list'),
    ], 'FundamentosPlay'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuestionListView.as_view(), name='question_change_list'),
        path('question/add/', teachers.question_add, name="question_add"),
        path('question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('question/approve/', teachers.QuestionApproveList.as_view(), name="to_approve_list"),
        path('question/approve/<int:question_pk>/', teachers.question_aprove_view, name='question_approve'),
        path('question/dimiss/<int:question_pk>/', teachers.question_dimiss, name='question_dimiss'),
        path('question/save/<int:question_pk>/', teachers.question_borrador, name='question_borrador'),
        path('question/filter/<str:filter>/', teachers.question_filter, name='question_filter'),
        path('question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('students/', teachers.MyStudentListView.as_view(), name='my_students'),
        path('students/approve', teachers.StudentListView.as_view(), name='students_to_approve'),
        path('students/progress/<int:student_pk>/', teachers.student_progress, name='student_progress'),
        path('students/<int:student_pk>/approve', teachers.student_approve, name='student_approve'),
        path('students/<int:student_pk>/dismiss', teachers.student_dismiss, name='student_dismiss')
    ], 'FundamentosPlay'), namespace='teachers')),





]

Proyecto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


from FundamentosPlay.views import home, students, teachers, assistant

urlpatterns = [
    path('', include('FundamentosPlay.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', home.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
  # path('accounts/signup/assistants/', assistant.AssistantSignUpView.as_view(), name='assistant_signup'),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FundamentosPlay/views/apiREST.py
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import  Response
from rest_framework import status, viewsets

from ..models import *


class Medallas(viewsets.ModelViewSet):

    def get(self,request,user_id):
        pass

        #serializador = ResultadoSerializer(resultados , many=True)
        #return  Response(serializador.data)

    def post(self):
        pass


class Leader(APIView):

	def get(self, request, id_leader):
		pass

FundamentosPlay/views/home.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from ..models import User, Estado, Dificultad


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    '''Estado.objects.all().delete()
    Dificultad.objects.all().delete()
    estado = Estado()
    estado.nombre="AP"
    estado2 = Estado()
    estado2.nombre = "PA"
    estado3 = Estado()
    estado3.nombre = "PC"
    estado4 = Estado()
    estado4.nombre = "BD"
    estado.save()
    estado2.save()
    estado3.save()
    estado4.save()
    d= Dificultad()
    d.name="Principiante"
    d.save()
    d2 = Dificultad()
    d2.name = "Intermedio"
    d2.save()
    d3 = Dificultad()
    d3.name = "Experto"
    d3.save()'''


    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:question_change_list')
        if request.user.is_assistant:
            return redirect('assistants:question_change_list')
        if request.user.is_student and request.user.is_active:
            return render(request, 'FundamentosPlay/home.html')
    return render(request, 'FundamentosPlay/home.html')


@login_required
def view_profile(request, username):
    user = request.user
    if (user.username != username):
        raise PermissionDenied
    try:
        usuario = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404("Usuario No existe")

    data = {'usuario': usuario}
    return render(request, 'FundamentosPlay/profile.html', data)


def noticias(request):
    return render(request, "FundamentosPlay/noticias.html", {'pagina':'Noticias'})


def informacion(request):
    return render(request, "FundamentosPlay/informacion.html", {'pagina':'Información'})


def leaderboard(request):
    return render(request, "FundamentosPlay/leaderboard.html", {'pagina':'LeaderBoard'})


def faq(request):
    return render(request, "FundamentosPlay/faq.html", {'pagina':'Preguntas Frecuentes'})


def descarga(request):
    return render(request, "FundamentosPlay/descarga.html", {'pagina':'Descarga'})

FundamentosPlay/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import  StudentSignUpForm
from ..models import  Student, User


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Estudiante'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        print("formulario valido")
        user = form.save()
        print("usuario creado")
        messages.success(self.request, 'Cuenta creada con éxito, podrá iniciar sesión cuando su profesor apruebe la cuenta')
        return render(self.request, 'FundamentosPlay/home.html')
def StadisticsView(request):
    return render(request, 'FundamentosPlay/home.html')

FundamentosPlay/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, ListView)

from ..forms import QuestionToCorrectForm
from ..decorators import teacher_required
from ..forms import BaseAnswerInlineFormSet, QuestionForm, TeacherSignUpForm, QuestionApproveForm
from ..models import Answer, Question,  User, Estado, Dificultad, Student
from django.core.mail import send_mail

#metodo para obtener los numeros de badges
def badges_counter(user):
    enviadas = Question.objects.filter(owner=user,estado__nombre="PA").count()
    aprobadas = Question.objects.filter(owner=user,estado__nombre="AP").count()
    borrador = Question.objects.filter(owner=user, estado__nombre="BD").count()
    porCorregir = Question.objects.filter(owner=user, estado__nombre="PC").count()
    usuariosPA= Student.objects.filter(teacher=user , user__is_active=False).count()
    questionsPA = Question.objects.filter(revisor=user , estado__nombre="PA").count()
    return {"PA":enviadas , "AP":aprobadas, "BD":borrador, "PC":porCorregir, "usersPA":usuariosPA, "questionsPA":questionsPA}


def send_email(para,asunto,mensaje):
    send_mail(
         asunto,
         mensaje,
        'fundamentosplaygame@gmail.com',
        [para],
        fail_silently=False,
    )
#Registro de profesores
class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Profesor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:question_change_list')



#Lista de perguntas totales
@method_decorator([login_required, teacher_required], name='dispatch')
class QuestionListView(ListView):

    ordering = ('fecha', )
    context_object_name = 'questions'
    template_name = 'FundamentosPlay/teachers/question_change_list.html'


    def get_queryset(self):
        queryset = self.request.user.questions.filter(owner=self.request.user)
        print(queryset)
        return queryset



    def get_context_data(self, **kwargs):
        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context


#Lista de preguntas por aprobar
@method_decorator([login_required, teacher_required], name='dispatch')
class QuestionApproveList(ListView):

    ordering = ('text', )
    context_object_name = 'to_approve'
    template_name = 'FundamentosPlay/teachers/question_to_approve_list.html'

    def get_queryset(self):
        queryset = Question.objects.filter(revisor__username=self.request.user , estado__nombre="PA")
        return queryset

    def get_context_data(self, **kwargs):
        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context




#vista para crear  pregunta  sin respuestas

@login_required
@teacher_required
def question_add(request):
    if request.method == 'POST':

        form = QuestionForm(request.user,None ,request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.owner = request.user
            estado =  Estado.objects.get(nombre="BD")
            question.estado =estado
            question.save()
            messages.success(request, 'Ahora podrá agregar  las respuestas y retroalimentaciones')
            return redirect('teachers:question_change', question.pk)
        else:
            messages.error(request, 'Todos los campos son obligatorios')
            form = QuestionForm(request.user,None)
            return render(request, 'FundamentosPlay/teachers/question_add_form.html', {'form': form })
    else:
        form = QuestionForm(request.user,None)

    return render(request, 'FundamentosPlay/teachers/question_add_form.html', {'form': form , 'counts': badges_counter(request.user)})



#vista para editar una pergunta
@login_required
@teacher_required
def question_change(request,  question_pk):

    question = Question.objects.get(pk=question_pk)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        fields=('text', 'is_correct', 'retroalimentacion'),
        formset=BaseAnswerInlineFormSet,

        min_num=2,
        validate_min=True,
        max_num=4,
        validate_max=True
    )
    if request.method == 'POST':

        if(question.estado.nombre =="PC"):
            print("por coregir  post")
            form = QuestionToCorrectForm(request.user, question, request.POST, instance=question)
            print(request.POST)
        else:
            form = QuestionForm(request.user ,question, request.POST, instance=question)
        formset = AnswerFormSet(question,request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            question = form.save(commit=False)
            question.estado = Estado.objects.get(nombre="PA")
            form.save()
            formset.save()
            send_email(question.revisor.email, "Pregunta Recibida",
                       question.owner.username + " Le ha enviado pregunta")
            messages.success(request, 'Pregunta enviada exitosamente!')
            return redirect('teachers:question_change_list')
        else:
            print("el form no es valido")
            print( form.errors)
            return render(request, 'FundamentosPlay/teachers/question_change_form.html', {
                'question': question,
                'form': form,
                'formset': formset,
                'counts': badges_counter(request.user)})
    else:
        if (question.estado.nombre == "PC"):
            form = QuestionToCorrectForm(request.user, question, instance=question)
        else:
            form = QuestionForm(request.user, question, instance=question)
        formset = AnswerFormSet(question,instance=question)
    return render(request, 'FundamentosPlay/teachers/question_change_form.html', {
        'question': question,
        'form': form,
        'formset': formset,
        'counts': badges_counter(request.user)})

#borrar una pregunta
@method_decorator([login_required, teacher_required], name='dispatch')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'question'
    success_url = reverse_lazy('teachers:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()



#vista  de  aprobar pregunta
@login_required
@teacher_required
def question_aprove_view(request,  question_pk):
    question = get_object_or_404(Question, pk=question_pk)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct','retroalimentacion'),
        min_num=2,
        validate_min=True,
        max_num=4,
        validate_max=True

    )

    if request.method == 'POST':
        form = QuestionApproveForm(request.POST, instance=question)
        formset = AnswerFormSet(question,request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                question = form.save(commit=False)
                estado = Estado.objects.get(nombre="AP")
                question.estado = estado
                form.save()
                formset.save()

            send_email(question.owner.email, "Pregunta Aprobada",question.revisor.username + " ha aprobado su pregunta")
            messages.success(request, 'Pregunta Aprobada exitosamente!')
            return redirect('teachers:to_approve_list')
    else:
        if(question.revisor == request.user):
            form = QuestionApproveForm(instance=question )
            formset = AnswerFormSet(question,instance=question)
        else:
            raise PermissionDenied

    return render(request, 'FundamentosPlay/teachers/question_approve_form.html', {
        'question': question,
        'form': form,
        'formset': formset,
        'counts': badges_counter(request.user)
    })



#accion de  rechazar pregunta
@login_required
@teacher_required
def question_dimiss(request ,question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    if request.method == 'POST':
        form = QuestionApproveForm(request.POST, instance=question)
        if form.is_valid():
            with transaction.atomic():
                question = form.save(commit=False)
                estado = Estado.objects.get(nombre="PC")
                question.estado = estado
                question.observacion= request.POST.get('observacion',"No se adjuntó observación")
                if(question.observacion!=""):
                    question.save()
                    send_email(question.owner.email, "Pregunta Rechazada",

FundamentosPlay/templates/FundamentosPlay/teachers/my_students.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Mis Estudiantes</li>
  </ol>
</nav>
<h2 class="mb-3">Mis Estudiantes</h2>

    <div class="card">
        <div class="table-responsive">
             <table class="table mb-0">
            <thead  class="thead thead-light">
              <tr>
                <th>Usuario</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for student in students %}
              <tr>
                  <td class="align-middle"><a href="{% url 'teachers:student_progress' student.user.pk %}">{{ student.user.username }}</a></td>
                  <td class="align-middle">{{ student.user.first_name}}</td>
                  <td class="align-middle">{{ student.user.last_name }}</td>
                </tr>
              {% empty %}
                <tr>
                  <td class="bg-light text-center font-italic" colspan="5">No tiene estudiantes.</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>


    </div>


{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/question_add_form.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}


{% load crispy_forms_tags %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change_list' %}">Mis Preguntas</a></li>
      <li class="breadcrumb-item active" aria-current="page">Crear un Pregunta</li>
    </ol>
  </nav>
  <h2 class="mb-3">Cree un nueva Pregunta</h2>
  <p class="lead">Agregue primero los detalles de la pregunta. En el siguiente paso podrá agregar las respuestas.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Crear</button>
  </form>
{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/question_change_form.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change_list' %}">Mis Preguntas</a></li>
      <li class="breadcrumb-item active" aria-current="page" id="qid">{{ question.id}}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate id="form">
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <table class="table">

        <tbody>
          {% for form in formset %}
          <tr>
            <td class="align-middle">
              <div class="col-2">
                {{ form.is_correct }}
              </div>
            </td>
            <td class="align-middle">
              <div class="col-5">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
              </div>
            </td>
            <td class="align-middle">
              <div class="col-5">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.retroalimentacion|as_crispy_field }}
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>

      </table>
    </div>
    <p>
      <small class="form-text text-muted">Su pregunta debe tener mínimo <strong>2</strong>  y máximo <strong>4</strong> respuestas. Elija al menos una respuesta correcta.</small>
    </p>
    {% if question.estado.nombre != "AP" %}
      <button type="submit" class="btn btn-success">Enviar</button>
      <button type="button" id="save" class="btn btn-outline-secondary">Guardar</button>
    {% endif %}


     {% if question.estado.nombre == "BD" %}
        <a href="{% url 'teachers:question_delete' question.id %}" class="delete btn btn-danger float-right">Borrar</a>
     {% endif %}

  </form>
{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/question_change_list.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Mis Preguntas</li>
  </ol>
</nav>
<h2 class="mb-3">Mis Preguntas</h2>
<!--
<a href="{% url 'teachers:question_add' %}" class="btn btn-primary mb-3" role="button">Crear Pregunta</a>
<a href="{% url 'teachers:to_approve_list' %}" class="btn btn-primary mb-3" role="button">Preguntas por Aprobar</a>
-->
    <section class="badge-tire container-fluid">
        <h4 class="tag">
            <span><a  href="{% url 'teachers:question_filter' 'PA' %}">Enviadas</a></span>
            <span class="badge badge-primary" style="background-color: blue; ">{{counts.PA}}</span>
        </h4>
        <h4 class="tag">
            <span><a  href="{% url 'teachers:question_filter' 'PC' %}">Por Corregir</a></span>
            <span class="badge badge-primary" style="background-color: red; ">{{counts.PC}}</span>
        </h4>
        <h4 class="tag">
            <span><a  href="{% url 'teachers:question_filter' 'BD' %}">Borrador</a></span>
            <span class="badge badge-primary" style="background-color: gray; ">{{counts.BD}}</span>
        </h4>
    </section>
    <br>
    <div class="card">

        <div class="table-responsive ">
             <table class="table mb-0">
            <thead  class="thead thead-light">
              <tr>
                <th>Contenido</th>
                <th>Nivel</th>
                <th>Dificultad</th>
                <th>Fecha</th>
                <th>Revisor</th>
                <th>Estado</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for question in questions %}
                 {% if question.estado.nombre == "AP" %}
                    <tr class="success">
                 {% elif question.estado.nombre == "PC" %}
                    <tr class="danger">
                 {% elif question.estado.nombre == "PA" %}
                    <tr class="info">
                 {% elif question.estado.nombre == "BD" %}
                    <tr class="active">
                  {% endif %}
                  <td class="align-middle"><a href="{% url 'teachers:question_change' question.pk %}">{{ question }}</a></td>
                  <td class="align-middle">{{ question.level}}</td>
                  <td class="align-middle">{{ question.Dificultad }}</td>
                  <td class="align-middle">{{ question.fecha}}</td>
                  <td class="align-middle">{{ question.revisor }}</td>
                  <td class="align-middle">{{ question.estado.get_html_badge}}</td>

                </tr>
              {% empty %}
                <tr>
                  <td class="bg-light text-center font-italic" colspan="5">No tiene preguntas, pulse Crear Pregunta .</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>


    </div>


{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/question_to_approve_list.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Preguntas Por Aprobar</li>
    </ol>
  </nav>
  <h2 class="mb-3">Preguntas Por Aprobar</h2>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Contenido</th>
          <th>Nivel</th>
          <th>Dificultad</th>
          <th>Fecha</th>
          <th>Creador</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for question in to_approve %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:question_approve' question.pk %}">{{ question.text }}</a></td>
            <td class="align-middle">{{ question.level}}</td>
            <td class="align-middle">{{ question.Dificultad }}</td>
            <td class="align-middle">{{ question.fecha}}</td>
            <td class="align-middle">{{ question.owner }}</td>

          </tr>
        {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="5">No tiene preguntas por aprobar.</td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/student_approve_list.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Estudiantes por Aprobar</li>
  </ol>
</nav>
<h2 class="mb-3">Estudiantes por Aprobar</h2>

<div class="card">
  <table class="table mb-0">
    <thead>
      <tr>
        <th>Usuario</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td class="align-middle">{{ student }}</td>
          <td class="align-middle">{{ student.user.first_name}}</td>
          <td class="align-middle">{{ student.user.last_name }}</td>
          <td class="text-right">
              <a  href="{% url 'teachers:student_approve' student.user.pk %}" class="btn ">✔</a>
              <a  href="{% url 'teachers:student_dismiss' student.user.pk %}" class="btn ">❌</a>
          </td>

        </tr>
      {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="5">No tiene estudiantes por aprobar .</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/teacher.html
{% extends 'FundamentosPlay/base_account.html' %}
{% load static %}
{% block menu %}
    <ul class="nav  navbar-nav navbar-vertical-align ">
        <li class="lititle active col-sm-12"><a href="#"><span class="glyphicon glyphicon-list-alt"></span>  Preguntas</a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:question_change_list' %}" class="menu-option"><span class="glyphicon glyphicon-list-alt"></span > Mis Perguntas</a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:question_add' %}" class="menu-option"><span class="glyphicon glyphicon-plus"></span>  Crear Pregunta </a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:question_filter' 'PC' %}" class="menu-option"><span class="glyphicon glyphicon-pencil"></span>  Corregir Preguntas <span class="badge">{{counts.PC}}</span></a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:question_filter' 'BD' %}" class="menu-option"><span class="glyphicon glyphicon-inbox"></span> Borrador</a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:to_approve_list' %}" class="menu-option"><span class="glyphicon glyphicon-ok"></span> Aprobar Preguntas<span class="badge">{{counts.questionsPA}}</span></a></li>

    </ul>

    <ul class="nav navbar-nav navbar-vertical-align">
        <li class="lititle active col-sm-12" ><a href="#"><span class="glyphicon glyphicon-user"></span>  Estudiantes</a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:my_students' %}" class="menu-option"><span class="glyphicon glyphicon-user"></span>  Mis Estudiantes</a></li>
        <li class="col-sm-12"><a href="{% url 'teachers:students_to_approve' %}" class="menu-option"><span class="glyphicon glyphicon-ok"></span>  Aprobar Estudiantes<span class="badge">{{counts.usersPA}}</span></a></li>

    </ul>
    <ul class="nav navbar-nav navbar-vertical-align">
        <li class=" lititle active col-sm-12"><a href="#"><span class="glyphicon glyphicon-stats"></span>  Estadísitcas</a></li>
        <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Mis Estadísticas</a></li>
        <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Estadísticas de Estudiantes</a></li>
        <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Estadísticas de Niveles</a></li>
    </ul>
{% endblock %}

{% block content %}
{% endblock %}

{% block scripts %}
<script src="{% static 'js/profesor.js' %}"></script>
{% endblock %}